### ISSUE TITLE
Provide a vcvarsall.bat equivalent environment hash.

### ISSUE THREAD

**Issue by MOZGIII** [mtwilliams/visual_studio#1]
Visual Studio has this `vcvarsall.bat` files that provide required environment variables (like `VSINSTALLDIR` and stuff).

It would be great if this gem would provide a hash with kay-value pairs to mimic the `vcvarsall.bat` behaviour to pass as `system()` first argument.

Or like this:

``` ruby
vs = VisualStudio.find 'vs2013'
env = {
  'MY_VAR' => 'MY_VALUE'
}.merge(vs.env)
system(env, "commad", "arg1", "etc...")
```

**Comment by mtwilliams** [comment]
I'm going to be improving and refactoring the new Visual Studio install detection, so feature requests are welcome!

To clarify, you want to be able to load the environment with `VCInstallDirs`, `WindowsSdkDir`, etc.? Seems reasonable to have in the library.

Perhaps via `VisualStudio::Install#environment`?

``` Ruby
vs = VisualStudio.find 'vs2013'
system(vs.environment, "cl.exe", "/showIncludes", ...)
```

I don't know what `vcvarsall.bat` defaults to, but that's what you would get if you didn't supply any arguments. If you want to target a specific architecture then you could specify `for`, like so: `vs.environment(for: 'x86_64')`.

**Comment by MOZGIII** [comment]
Yes, that would be useful.
It would also be great to have a separate method to merge with existing (passed as an argument) environtent, because if I'd like to pass my own `PATH` I would need to merge in manually by adding the value from the lib's env to the one I have, separating it with `;`.
It is quite simple with `PATH`, cause `PATH` is a well known variable of that kind (list variable), but in general there could be more of those varibales and there could be more kinds of variables (not just lists - i.e. flags are also possible).
It would be a good idea to provide a convenient function to merge two environments together, that would treat known (VS-related) non-simple kinds of variables in the correct way (in example merge `PATH`s but overwrite (or merge?) `VCInstallDirs`).
Maybe that's not very relevant yet, since so far there is only `PATH` that everyone knows about.

**Comment by mtwilliams** [comment]
Just use [Hash#merge](http://ruby-doc.org/core-1.9.3/Hash.html#method-i-merge) for that:

``` Ruby
vs = VisualStudio.find 'vs2013'
env = ENV.to_h.merge(vs.environment) do |k, lhs, rhs|
  return ['VCInstallDir', 'WindowsSdkDir'].include?(k) ? rhs : lhs
end
system(env, "cl.exe", "/showIncludes", ...)
```

**Comment by MOZGIII** [comment]
That's not the point.
The problem is `Hash#merge` can't merge list variables (like `PATH`) - the "merge" semantics is different for them that just adding key if it's missing. Also, `Hash` by itself does not store or take into account value types (nither in the implementation nor by design) when it merges them.
For now, there is only `PATH`, but maybe there are more (I haven't quite digged in it yet). As a gem user, I don't really need to know which environment variables are lists and which are not, but it would probably be a good idea to think about a generic way to lat user provide it's own configuration.
Well, on the second though, it seems to be too generic to implement. To be more specific here, one would need more experience with VS-related build systems.

**Comment by mtwilliams** [comment]
Well, you can use your favorite deep merge:

``` Ruby
require "active_support/core_ext/hash/deep_merge"
vs = VisualStudio.find 'vs2013'
env = ENV.to_h.deep_merge(vs.environment)
system(env, "cl.exe", "/showIncludes", ...)
```

**Comment by mtwilliams** [comment]
I see some value in having the "smart merge" in this Gem, as it is a black-box infrastructure piece for using Visual Studio.

``` Ruby
vs = VisualStudio.find 'vs2013'
env = vs.environment for: 'x86_64', base: ENV
system(env, "cl.exe", "/showIncludes", ...)
```

**Comment by MOZGIII** [comment]
Well, `deep_merge` is great but not relevent.

Your last example shows only one usecase:

``` ruby
vs = VisualStudio.find 'vs2013'
env = vs.environment for: 'x86_64', base: ENV
system(env, "cl.exe", "/showIncludes", ...)
```

User wants to extend his configuration with the one provided by `gem`.

The other one:

``` ruby
env_from_config = SomeConfig.get_env
vs = VisualStudio.find 'vs2013'
env = vs.environment for: 'x86_64', overlay: env_from_config 
system(env, "cl.exe", "/showIncludes", ...)
```

Now, user wants to take what `gem` provides as a base, and "smart merge" provided configuration with his options. Notice, the first time _user_ provided the base, and now it's the _gem_ that provides the base.

Generally the same rules apply for both cases, you could probably even combine them:

``` ruby
env_from_config = SomeConfig.get_env
vs = VisualStudio.find 'vs2013'
env = vs.environment for: 'x86_64', base: ENV, overlay: env_from_config 
system(env, "cl.exe", "/showIncludes", ...)
```

My idea was that it should be a generic `VisualStudio#merge_env` for that, since API really should be two-way, and may not include environment from the gem at all:

``` ruby
vs = VisualStudio.find 'vs2013'
config_one = SomeConfig.get_env
config_two = SomeOtherConfig.get_env
env = vs.merge_env(config_one, config_two)
system(env, "cl.exe", "/showIncludes", ...)
```

The use with environment provided by the gem:

``` ruby
vs = VisualStudio.find 'vs2013'
project_config = SomeConfig.get_env
env = vs.merge_env vs.environment(for: 'x86_64'), project_config
system(env, "cl.exe", "/showIncludes", ...)
```

And with all usecases combined:

``` ruby
vs = VisualStudio.find 'vs2013'
global_config = GlobalConfig.get_env
project_config = ProjectConfig.get_env
env = vs.merge_env global_config, vs.environment(for: 'x86_64')
env = vs.merge_env env, project_config
system(env, "cl.exe", "/showIncludes", ...)
```

**Comment by mtwilliams** [comment]
Ah, I see what you're getting at. Completely agree.

The cleanest implementation is to put the merge logic, with ride-side precedence, in `VisualStudio::Environment.merge` and provide shortcuts via `base` and `overlay` options when using `VisualStudio::Install#environment`.

Unfortunately, that would result in more typing as per your last example. Since Ruby is kind, you could always:

``` Ruby
merge_env = VisualStudio::Environment.merge
# ...
env = merge_env global_config, vs.environment(for: 'x86_64')
env = merge_env env, project_config
system(env, "cl.exe", "/showIncludes", ...)
```

More likely you'll refactor the environment merging logic into a helper called something like `BuildEnvironment` or into `ProjectConfig` because you'll have to special-case for other tools anyway:

``` Ruby
class BuildEnvironment
  def merge(...)
    VisualStudio::Environment.merge(...)
    XCode::Environment.merge(...)
    MarmaladeSDK::Environment.merge(...)
  end
end
```

That makes me wonder if providing a method that only merges what it knows would be worthwhile.

**Comment by MOZGIII** [comment]
Probably more like this:

``` ruby
class BuildEnvironment
  def merge(base = {})
    env = base
    env = VisualStudio::Environment.merge(env, @config.vs.environment(for: @config.architecture))
    env = XCode::Environment.merge(env, ...)
    env = MarmaladeSDK::Environment.merge(env, ...)
    env
  end
end
```

But that would require all of them to follow the same contract. Given that, it's possible to even build middleware stacks around env generation. But the scope of this gem, I guess, is to just do good job with Visual Studio.

By the way, with your code snippet (simplified to show the point):

``` ruby
merge_env = Whatever.merge
... = merge_env(..., ...)
```

How is it possible to call a variable as a function? I haven't tracked changes to the language for quite some time, is it new syntax?

**Comment by mtwilliams** [comment]
Sorry, the code-snippet is incorrect; I'm switching languages so often now I can't remember what I can do in them.

You can achieve that via `method`:

```
$ irb                                                  
irb(main):001:0> def meaning_of_life                   
irb(main):002:1>   42                                  
irb(main):003:1>   end                                 
=> :meaning_of_life                                    
irb(main):004:0> what_is_the = meaning_of_life         
=> 42                                                  
irb(main):005:0> what_is_the.class                     
=> Fixnum                                              
irb(main):006:0> what_is_the = method(:meaning_of_life)
=> #<Method: Object#meaning_of_life>                   
irb(main):007:0> what_is_the.()                        
=> 42                                                  
irb(main):008:0> what_is_the.class                     
=> Method
```

Not too pretty, so alternatively:

``` Ruby
def merge_env(lhs, rhs)
  VisualStudio::Environment.merge(lhs, rhs)
end
```

**Comment by MOZGIII** [comment]
Yeah, that would work.

Overall, I pretty much like the idea of implementing a separate `VisualStudio::Environment.merge` plus `vs.environment(base: ..., overlay: ...)` helpers.

That's if `VisualStudio::Environment` is a module, not a class, so we do not introduce a type - I guess we should be using plain `Hash` here.

**Comment by mtwilliams** [comment]
I've looked into `vcvarsall.bat` and friends. They're quite complex.

An initial implementation could be achieved with minimal fuss by building a temporary batch-file that calls `vcvarsall.bat` (with the correct arguments) and then dumps the environment. This should reduce the risk of us missing hidden environment variables that would break the toolchain in mysterious ways. Of course, `VisualStudio::Environment` will still need to consciously merge the odd variables, but my gut tells me that they're easy to figure out (things like paths) and the task will be (relatively) easy.

Going this route has the benefit of reducing code complexity, because the environment changes a lot between different versions of Visual Studio.

There is one standout issue I do see with this, is that you can't easily prescribe which Windows SDK you would prefer. Doing so would necessitate a fully custom implementation. This is something that [Ryb](https://github.com/mtwilliams/ryb) needs.

**Comment by MOZGIII** [comment]
That would do the trick, I guess.
Could we explicitly mix the user's choice about Windows SDK variant after the env is acquired from `vcvarsall.bat`?

**Comment by mtwilliams** [comment]
That would be counter-productive. A lot of environment variables are set based on the Windows SDK. We would have to parse those environment variables, filter out the values tied to that variant and replace them with our own. It might be worth it to just implement the logic internally from the get-go.

What do your use cases look like, @MOZGIII? For me, at least right now, it is compiling C and C++ code for Windows desktop. I will probably need to compile C# as well, in a few months.

**Comment by MOZGIII** [comment]
Honestly, the only practical use case I've implemented so far is to run an external program from my code as if it's run from Visual Studio\s comaand prompt that needs all this info to just copy out the `vcredist_x86.exe` for deployment package.
That's what I got so far.
In the future I'd like to implement a build system that would comptile my C++/Qt 5 app, and that's where this gem comes in again... Probably rebuilding the Qt itself is also a thing I'd do, and that would require Windows SDK (for Angle). I'd need builds for both x86 and x64.
No plans on C# and other stuff, however that's dut to lack of current project to work on, and it would be great to play with them.
The bigger and overall idea of mine for which I need this gem is to be able to fully automate build process, like from starting a VM with no OS in there, to installing Windows and VS, to eventually pulling the code (both the Qt library and my application), building it, running tests and the deploying the artifacts somewhere else (i.e. to the automatic release system or QA team - have no idea of that part for now).

**Comment by MOZGIII** [comment]
Here's my stuff by the way https://github.com/MOZGIII/qt-deploy-win

**Comment by mtwilliams** [comment]
Ha, that's actually my end goal too! I want to provision a virtual machine to build my C/C++ (and C#) code, package artifacts, and upload. I also want to do a similar thing for workstations.

I haven't done much work with Qt, so correct me if I'm wrong. I looked over your code and it appears that your using a Qt tool that handles the "deploy" for you (and that requires the environment to be setup)?

**Comment by MOZGIII** [comment]
Yes. What it does is just copies all Qt `.dll`s and other stuff into a single directory based on precompiled executable, and yes, that requires to VS command prompt, even though the code have to be already built at this point. Not the actual deploy, but the "deploy" in terms of that Qt's tools.
This one would be just a part of a build system for Windows, to be run between building the code and packaging to the installers and updaters' diffs.

I've also played already a bit with packer for VM provisioning. Check this out if you're interested: https://github.com/joefitzgerald/packer-windows

**Comment by mtwilliams** [comment]
I see.

I'm wondering if maybe another method should be exposed to run a command under the "VS Command Prompt" environment:

``` Ruby
VisualStudio.find('vs2013').cmd(...)
```

Also, thanks for that link. I'll look into it.

**Comment by MOZGIII** [comment]
I don't think a method to run something from a command prompt would be useful - there are too many ways to run the program in ruby. Its much more robust for a gem to just provide useful agruments for those calls.

**Comment by mtwilliams** [comment]
Good point.
