### ISSUE TITLE
We don't need to use a delimiter VisualStudio::Product#environment

### ISSUE THREAD

**Issue by mtwilliams** [mtwilliams/visual_studio#2]
I'm referring to [this code](https://github.com/mtwilliams/visual_studio/blob/0900e1c09cc878d88cddc525b83399f2153cb606/lib/visual_studio/product.rb#L43).

**Comment by MOZGIII** [comment]
How about adding output redirection for the `vcvarsall.bat` call to `/dev/null`?
Syntax for Windows is as follows:

```
command > nul 2>&1
```

**Comment by mtwilliams** [comment]
Success case is denoted by a zero `status`. The batch file only bitches when something borked. In other words, superfluous.

**Comment by MOZGIII** [comment]
Okay :)
